[package]
name = "first_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
log_lib = { path = "../log_lib" }

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
