[package]
name = "second_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
first_lib = { path = "../first_lib" }
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
